# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ee606fc989905d17d4dc8510749fa79733edd9b7e82ca3b627950c3838de1289d3a18bcfc9c46e8e46e54da1513e75f5512aef513055ebaa5f7dd46ad61f645

test:
  secret_key_base: 170e8a3badb43081704d57acc700a034176700764bf90a96f3d50dc0b379e457b68445d97cd8c2458f4eafcea7c6649608bfad736786a5b1b115ff09ecb3f758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
